#!/bin/bash
#
# Detect AprilTag in a single image. Usage:
#
# ./analyze_image <image_load_path> <image_save_path>
#

ros2 launch apriltag_ros single_image_client.launch.py image_load_path:="$1" image_save_path:="$2"
